### ISSUE TITLE
ChRIS @ NMR

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/projectman#24] opened 2015-02-11 22:12 UTC
# ChRIS @ NMR

Needs to be resurrected pending kaos/tesla re-integration into NMR network.

**Comment by NicolasRannou** [comment] 2015-02-12 07:14
Needs #23 to be addressed

**Comment by rudolphpienaar** [comment] 2015-02-13 21:08
Started VM on 'tesla' and kept getting errors:

error: invalid arch-independent ELF magic...

**Comment by rudolphpienaar** [comment] 2015-02-13 21:58
Downloaded live image and tried various grub reinstall options. None worked. 
Now attempting to do an in-line upgrade from 14.01 to 14.10 using live CD

**Comment by NicolasRannou** [comment] 2015-02-16 08:02
Upgrading/reinstalling Tesla or the ChRIS VM?

**Comment by NicolasRannou** [comment] 2015-02-24 13:23
@rudolphpienaar 

OK, so NMR infrastructure is almost restored, except for a big omission -- chris.

I couldn't get the original VM up and running again, so made a new one. It's up (chris.nmr.mgh.harvard.edu) and integrated into the NMR NIS etc.

@jbernal0019  can you start checking out a fresh build of ChRIS on that machine? @nicolasrannou, and can you take a look when you're on-line again?

To access, from BCH:

ssh -X -p 1148 chris@tautona

**Comment by NicolasRannou** [comment] 2015-02-24 13:24
@jbernal0019 

I've done all the VM config in NMR up to section 1.1.3.6 of the wiki :

http://durban/wiki/index.php/ChRISMEGABUNDLE

When I restart the Apache web server I keep getting this message on the terminal:

Restarting web server apache2  
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
                                                                                            [ OK ]

Now the neuroimage packages must be installed and plugin.conf and config.inc.php configured.

**Comment by NicolasRannou** [comment] 2015-02-24 13:24
@rudolphpienaar 

OK -- sounds good... I don't think any packages need to be installed since they're all available to the VM from the NMR NFS... I think the plugin.conf just needs to be appropriately configured, right?

**Comment by NicolasRannou** [comment] 2015-02-24 13:27
OK so now I will update the configuration file to see if it works as expected.

General Configuration file: 
https://github.com/FNNDSC/chrisreloaded/blob/master/config/chris-mgh_config.inc.php

Plugin Configuration file:
https://github.com/FNNDSC/chrisreloaded/blob/master/config/chris-mgh_plugin.conf

**Comment by NicolasRannou** [comment] 2015-02-24 15:36
dicom listener on chris:
updated the listening port on chris to 10401 for consitency

needs to setup xinetd on kaos to redirect traffic from kaos 10401 to chris 10401

**Comment by NicolasRannou** [comment] 2015-02-24 15:45
dicom listener fixed.

There was a typo in the xinetd chrislistener.

Was

```
service chrislistener
{
    socket_type = stream
    wait = no
    user = chris
    group = chris
    log_on_success = HOST DURATION
    log_on_failure = HOST
    server = /home/chris/src/chrisreloaded/controller/pacs.listener.php
    disable = no
    port 10401
}
```

Instead of:

```
service chrislistener
{
    socket_type = stream
    wait = no
    user = chris
    group = chris
    log_on_success = HOST DURATION
    log_on_failure = HOST
    server = /home/chris/src/chrisreloaded/controller/pacs.listener.php
    disable = no
    port = 10401
}
```

Notice the missing "=" on the port line.

**Comment by NicolasRannou** [comment] 2015-02-24 15:56
tautona:1143 now displays home page as expected.

Some missing information in the wiki about ssl configuration:
http://durban/wiki/index.php/ChRISMEGABUNDLE#config_apache2

```
$>sudo vim /etc/apache2/sites-available/default-ssl.conf
 ...
           # START OF CHRIS MODIFICATIONS
           # DocumentRoot /var/www/html
           DocumentRoot /var/www
           <Directory />
               Options FollowSymLinks
               AllowOverride None
           </Directory>
           <Directory /var/www/>
               Options Indexes FollowSymLinks MultiViews
               AllowOverride None
               Order allow,deny
               allow from all
           </Directory>
           # END OF CHRIS MODIFICATIONS
 ...
 $>sudo service apache2 restart
```

**Comment by rudolphpienaar** [comment] 2015-02-24 19:09
# Following issues still remain:
- forward traffic from kaos:10401 to chris:10401
  - pacs_pull plugin won't work.
- no id_rsa or id_rsa.pub in user config directory (is this a directory/perms issue?)
  - no plugins will work since self (or password less) ssh isn't working without those files

**Comment by rudolphpienaar** [comment] 2015-02-24 19:12
# Post setup notes

The following had to be done in the VM (should be added to wiki):
1. On fresh checkout directory and file permissions are too prohibitive:

```
find . -type d -exec chmod o+wx {} \;
find . -type f -exec chmod o+r {} \;
```
1. Plugins are not executable by non-chris user. 

```
cd ~chris/src/chrisreloaded/plugins
find . -maxdepth 1 -mindepth 1 -type d -exec chmod o+x {}/{} \;
```

**Comment by NicolasRannou** [comment] 2015-02-25 13:50
passwordless ssh appears to work, it is the expected behavior not to have the ssh key appearing the config directory anymore.

**Comment by NicolasRannou** [comment] 2015-02-25 13:50
chris.run is not being executed on the cluster ~ investigating.

might be fixed with the crun fix below

**Comment by NicolasRannou** [comment] 2015-02-25 13:51
FIXED: some pythons libraries are missing in the chris/lib/py directory. At least arg parse is missing.
cp /usr/lib/python2.7/argparse.py ~/lib/py/

[rudolph@launchpad:x86_64-Linux]~$>/space/chris/1/src/chrisreloaded/plugins/mri_convert/mri_convert --input /space/chris/1/users/rudolph/mri_convert/2_25_2015_14_14_59-8/0_14.10.21_08_26_27_DST_1.3.12.2.1107.5.2.19.45407-044Y-O/_chrisInput_//space/chris/1/users/rudolph/file_browser/2_24_2015_13_53_8-4/0_2015-02-24-13-53-08/data-old/14.10.21_08_26_27_DST_1.3.12.2.1107.5.2.19.45407-297/2014.10.21-044Y-MGH_QA-335/epi_stability_multi_sPlot-epi_stability_multi_sPlot-890/0001-1.3.12.2.1107.5.2.19.45407.2014102109445136371271968.dcm --format "nii" --extensions "nii,mgz,dcm,mgh" --freesurferscript "/space/chris/1/packages/scripts/nmr-fs" --output /space/chris/1/users/rudolph/mri_convert/2_25_2015_14_14_59-8/0_14.10.21_08_26_27_DST_1.3.12.2.1107.5.2.19.45407-044Y-0
Traceback (most recent call last):
  File "/space/chris/1/src/chrisreloaded/plugins/mri_convert/mri_convert", line 17, in <module>
    from plugin import Plugin
  File "/space/chris/1/src/chrisreloaded/plugins/mri_convert/../plugin.py", line 31, in <module>
    from argparse import ArgumentParser
ImportError: No module named argparse

**Comment by NicolasRannou** [comment] 2015-02-25 13:59
FIXED: crun needs to be executable by anybody.
chmod 755 chrisreloaded/lib/_common/crun.py

[rudolph@launchpad:x86_64-Linux]~$>source /space/chris/1/users/rudolph/mri_convert/2_25_2015_14_55_25-9/0_14.10.21_08_26_27_DST_1.3.12.2.1107.5.2.19.45407-044Y-O/_chrisRun_/chris.env && /space/chris/1/src/chrisreloaded/lib/_common/crun.py -u rudolph --host launchpad -s crun_hpc_launchpad --saveJobID /space/chris/1/users/rudolph/mri_convert/2_25_2015_14_55_25-9/0_14.10.21_08_26_27_DST_1.3.12.2.1107.5.2.19.45407-044Y-O/_chrisRun_ -c '\'' /bin/bash /space/chris/1/users/rudolph/mri_convert/2_25_2015_14_55_25-9/0_14.10.21_08_26_27_DST_1.3.12.2.1107.5.2.19.45407-044Y-O/_chrisRun_/chris.run '\''
-bash: /space/chris/1/src/chrisreloaded/lib/_common/crun.py: Permission denied

**Comment by NicolasRannou** [comment] 2015-02-25 14:11
FIXED: chris tmp dir must be 777
chmod 777 tmp

(special permission to allow everybody to write but only owner to delete?)

**Comment by NicolasRannou** [comment] 2015-02-25 14:14
FIXED: curl was not installed on chris VM
sudo apt-get install curl

**Comment by NicolasRannou** [comment] 2015-02-25 14:18
FIXED: wrong permissions in scripts directory - should be 755
chmod -R 755 scripts/*

/space/chris/1/users/rudolph/mri_convert/2_25_2015_15_14_33-12/0_3045698-014Y-M/_chrisRun_/DIFFUSION-DIFFUSION-158.run: line 10: mri_convert: command not found

[rudolph@launchpad:x86_64-Linux]/$>source /space/chris/1/packages/scripts/nmr-fs stable;
-bash: /space/chris/1/packages/scripts/nmr-fs: Permission denied

**Comment by NicolasRannou** [comment] 2015-02-25 14:28
FIXED: wrong permissions of the scripts directory itself
chmod -R 755 scripts

**Comment by NicolasRannou** [comment] 2015-02-25 14:53
FIXED: DICOM Listener port forwarding

nc localhost 10401 hanging on kaos

```
toor@kaos$> cat /etc/services
...
# Local services
chrislistener   10401/tcp   # DICOM - CHRIS listener
chrislistener   10401/udp   # DICOM - CHRIS listener
```

```
toor@kaos$> cat /etc/xinetd.d/chrislistener
service chrislistener
 {
    socket_type         = stream
    wait                = no
    user                = chris
    group               = chris
    log_on_success      = HOST DURATION
    log_on_failure      = HOST
    redirect            = chris 10401
    disable             = no
    port                = 10401
 }
```

**Comment by rudolphpienaar** [comment] 2015-02-25 19:48
In the chris scripts dir, there are no submodules, so no '_common' directory... This is not critical, but not the expected behavior.

**Comment by NicolasRannou** [comment] 2015-02-26 10:54
yes... I think what "saves" us is the _common directory being part of chrisreloaded/lib and added to the path.

**Comment by NicolasRannou** [comment] 2015-02-26 10:57
there was more permissions issues because the chris user has a umask 027 and we were expecting 022
https://github.com/FNNDSC/chrisreloaded/commit/04dd1c46fab6ffeede96017b2c4003da174850f6

**Comment by NicolasRannou** [comment] 2015-02-26 10:57
launchpad is down...

to be more specific, jobs are just hanging in the queue now.

```
[rudolph@launchpad:x86_64-Linux]~$>qstat | grep -w rudolph
7720000.launchpad          pbsjob_17        rudolph                0 Q max200         
7720048.launchpad          pbsjob_18        rudolph                0 Q max200         
7720053.launchpad          pbsjob_19        rudolph                0 Q max200         
7720057.launchpad          pbsjob_20        rudolph                0 Q max200
```

**Comment by NicolasRannou** [comment] 2015-02-27 12:50
OK it went through.

Still have to test:
- find session
- recon all
- tractography
- pacs push (from NRM to BCH)
- pacs push (from BCH to NMR)

Note: pacs push needs a passwordless ssh connection from one host to another, in both directions

**Comment by NicolasRannou** [comment] 2015-02-27 16:34
Also need to update the .chris.conf

**Comment by NicolasRannou** [comment] 2015-03-03 06:57
Find session seems to work. A problem appears with the pacs_push bash script. Sometimes, it doesn't want to push the data ad just makes the whole thing crash.

**Comment by NicolasRannou** [comment] 2015-03-03 16:28
ssh connection:
17:26 rudolphpienaar: from BCH: chris connects to tautona:1148 for chris_push
17:26 rudolphpienaar: from NMR: chris@nmr connects to kaos:2214 for chris_push to BCH

**Comment by NicolasRannou** [comment] 2015-03-03 16:29
pacs ports
17:28 rudolphpienaar: NMR --> BCH: chris@nmr connects to kaos:10402
17:28 rudolphpienaar: BCH --> NMR: chris@bch connects to tautona:10301

**Comment by NicolasRannou** [comment] 2015-03-03 16:38
passwordless connection between chris BCH and chris NMR setup for chris user

**Comment by NicolasRannou** [comment] 2015-03-03 16:43
chris nmr configuration updated

still needs to update pacs server IP, etc.

**Comment by NicolasRannou** [comment] 2015-03-06 08:33
server IP updated.

pacs_push to be tested next

**Comment by NicolasRannou** [comment] 2015-03-06 08:34
@rudolphpienaar did you receive any email after I did a pacs_push from BCH yesterday?

It seems the data arrived at MGH. Or is the email serive not hooked up yet?

**Comment by rudolphpienaar** [comment] 2015-03-06 15:24
I don't think I got any emails! I'll look at the ChRIS setup...

**Comment by rudolphpienaar** [comment] 2015-03-06 15:24
I mean the chris VM machine, not the web service!

**Comment by NicolasRannou** [comment] 2015-03-09 09:08
makes sense, I was testing the pacs_push not the chris_push, I got confused :)

**Comment by NicolasRannou** [comment] 2015-03-20 08:09
issues with tractography: link to fsl eddy correction chris/bin -> /home/chris instead /space/1/chris/...

**Comment by NicolasRannou** [comment] 2015-03-20 09:09
we now use the fsl and dtk provided by nmr directly.

**Closed as completed** 2015-09-01 07:23 UTC
Labels: chris, deploy, wiki
